# Generated by Django 3.2.7 on 2021-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210928_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='health', max_length=200),
        ),
        migrations.AlterField(
            model_name='health',
            name='name',
            field=models.CharField(blank=True, default='health', max_length=200),
        ),
        migrations.AlterField(
            model_name='police',
            name='name',
            field=models.CharField(blank=True, default='health', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
