# Generated by Django 3.2.7 on 2021-09-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_health_police'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='police',
            old_name='Contact',
            new_name='contact',
        ),
    ]
