# Generated by Django 3.2.7 on 2021-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_users_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
    ]
