# Generated by Django 3.2.7 on 2021-09-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_users_neighborhood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name_plural': 'Health'},
        ),
        migrations.AlterModelOptions(
            name='police',
            options={'verbose_name_plural': 'Police'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
