# Generated by Django 3.2.7 on 2021-09-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_users_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.neighborhood'),
        ),
    ]
